rvm:
  - 2.7
  - 3.0
notifications:
  webhooks: https://coveralls.io/webhook
script:
  - ./script.sh
jobs:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: focal
